<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxl2MXs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxl2MXs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxl2MXs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxl2MXs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxl2MXs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Oxl2MXs',
    'container.build_id' => '21114c50',
    'container.build_time' => 1702493038,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxl2MXs');
