<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN30pzxS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN30pzxS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN30pzxS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN30pzxS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN30pzxS\App_KernelDevDebugContainer([
    'container.build_hash' => 'N30pzxS',
    'container.build_id' => 'fd088d22',
    'container.build_time' => 1702917843,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN30pzxS');
